export default {
  CLICK_CATEGORY: 'CLICK_CATEGORY',
  CLICK_POST: 'CLICK_POST',
  SET_CATEGORY: 'SET_CATEGORY',
  DOWNLOAD_CATEGORY: 'DOWNLOAD_CATEGORY',
  DOWNLOAD_REQUEST_CATEGORY: 'DOWNLOAD_REQUEST_CATEGORY',
  DOWNLOAD_REJECT_CATEGORY: 'DOWNLOAD_REJECT_CATEGORY'
};
