export default {
  CLICK_PERSONALIZATION: 'CLICK_PERSONALIZATION',
  SET_PERSONALIZATION: 'SET_PERSONALIZATION',
  DOWNLOAD_PERSONALIZATION: 'DOWNLOAD_PERSONALIZATION',
  DOWNLOAD_REQUEST_PERSONALIZATION: 'DOWNLOAD_REQUEST_PERSONALIZATION',
  DOWNLOAD_REJECT_PERSONALIZATION: 'DOWNLOAD_REJECT_PERSONALIZATION'
};
