export default {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  EDIT_ACTIVATE_TODO: 'EDIT_ACTIVATE_TODO',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
  GET_REQUESTED_TODO: 'GET_REQUESTED_TODO',
  GET_FULFILLED_TODO: 'GET_FULFILLED_TODO',
  GET_REJECTED_TODO: 'GET_REJECTED_TODO',
  PUSH_REQUESTED_TODO: 'PUSH_REQUESTED_TODO',
  PUSH_REJECTED_TODO: 'PUSH_REJECTED_TODO',
  UPDATE_REQUESTED_TODO: 'UPDATE_REQUESTED_TODO',
  UPDATE_REJECTED_TODO: 'UPDATE_REJECTED_TODO',
  UPDATE_TOGGLE_REQUESTED_TODO: 'UPDATE_TOGGLE_REQUESTED_TODO',
  UPDATE_TOGGLE_REJECTED_TODO: 'UPDATE_TOGGLE_REJECTED_TODO',
  DELETE_REQUESTED_TODO: 'DELETE_REQUESTED_TODO',
  DELETE_REJECTED_TODO: 'DELETE_REJECTED_TODO',
  VisibilityFilters: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
  },
};
