export default {
  MOVE_WIDGET: 'MOVE_WIDGET',
  SET_WIDGET: 'SET_WIDGET',
  SET_REJECTED_WIDGET: 'SET_REJECTED_WIDGET',
  UPDATE_REJECTED_WIDGET: 'UPDATE_REJECTED_WIDGET',
  UPDATE_REQUESTED_WIDGET: 'UPDATE_REQUESTED_WIDGET'
};
